baseURL = "https://dhiresearch.com/"
languageCode = "en-us"
title = "Dhi: Research"
theme = "congo"

[params]
  # This hides the default homepage profile layout
  homepage.layout = "page"
  header.logo = "images/dhi.jpg"

  header.showMenu = false
  header.showSearch = false
  header.showTitle = false
  header.showLogo = false

[params.article]
  # This removes the clickable '#' links next to headers
  showHeadingAnchors = false

[markup.goldmark.renderer]
  # Crucial: This allows using <div> tags for the side-by-side layout
  unsafe = true


